feat/transactionstatus
Zilliqa/Zilliqa-JavaScript-Library pull request #269
Opened 2020-12-11 03:30 UTC by renlulu

## Description
To support new API https://github.com/Zilliqa/dev-portal/pull/121/files

## Review Suggestion

## Status

### Implementation

- [x] **ready for review**

2020-12-11 03:56 UTC, ansnunez requested changes

2020-12-11 03:56 UTC, ansnunez commented on examples/queryTransactionStatus.js
> +//  Copyright (C) 2018 Zilliqa
Change date to 2020?

2020-12-11 13:15 UTC, renlulu commented on examples/queryTransactionStatus.js
> +//  Copyright (C) 2018 Zilliqa
Oh, ok!

2020-12-12 08:46 UTC, teye approved these changes

2020-12-15 08:22 UTC, bb111189 approved these changes

2020-12-15 08:23 UTC, merged