feat/offline-signing
Zilliqa/Zilliqa-JavaScript-Library pull request #278
Opened 2021-02-02 11:05 UTC by teye

### Description
This pr is a feature request for #275 Offline Signing.

Internet connection is required for wallet signing due to the presence of `GetBalance` call which obtains the latest nonce for the Transaction object to be signed. This pr gives developers the option to bypass the `GetBalance` call by declaring a flag to toggle offline signing on/off.

The only caveat is that a nonce must be supplied by the developers should they opt for offline signing. 

### Updated Methods
```
sign(transaction: Transaction, offlineSign?: boolean)
signWith(transaction: Transaction, address: string, offlineSigning?: boolean)
```

### Tests
```
yarn install
yarn bootstrap
node [project_dir]/examples/node/walletSign.js
```

2021-02-03 10:00 UTC, bb111189 requested changes

2021-02-03 10:00 UTC, bb111189 commented on packages/zilliqa-js-account/README.md
> +- `offlineSign`: `boolean` (optional) - toggles offline signing on/off. If set to `true`, offline mode is used and does not require internet connection to sign a transaction.
maybe can highlight default is false

2021-02-04 02:01 UTC, teye commented on packages/zilliqa-js-account/README.md
> +- `offlineSign`: `boolean` (optional) - toggles offline signing on/off. If set to `true`, offline mode is used and does not require internet connection to sign a transaction.
updated

2021-02-04 13:36 UTC, renlulu approved these changes

2021-02-05 03:52 UTC, bb111189 approved these changes

2021-02-05 03:53 UTC, merged