chore: update code for get pending txn
Zilliqa/Zilliqa-JavaScript-Library pull request #292
Opened 2021-04-19 12:28 UTC by renlulu

## Description
Update error map for GetPendingTxn according to https://dev.zilliqa.com/docs/apis/api-transaction-get-transaction-status/

## Review Suggestion

## Status

### Implementation

- [ ] **ready for review**

2021-04-19 13:29 UTC, micovi approved these changes

2021-04-20 02:24 UTC, bb111189 commented
We will need to remove getpendingtxn and retain getpendingtxns

2021-04-20 02:25 UTC, bb111189 requested changes
check comments

2021-04-20 02:30 UTC, teye approved these changes

2021-04-26 09:50 UTC, bb111189 approved these changes

2021-04-26 09:50 UTC, merged