Create codeql-analysis.yml
Zilliqa/Zilliqa-JavaScript-Library pull request #382
Opened 2021-09-09 02:51 UTC by noel-yoo

## Description
This PR uses [CodeQL](https://securitylab.github.com/tools/codeql/).

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] Add tests to cover changes as needed.
- [ ] Update documentation as needed.

2021-09-16 06:05 UTC, bb111189 requested changes

2021-09-16 06:05 UTC, bb111189 commented on .github/workflows/codeql-analysis.yml
> +    branches: [ dev, master ]
no master branch in this repo

2021-09-16 06:14 UTC, noel-yoo commented on .github/workflows/codeql-analysis.yml
> +    branches: [ dev, master ]
sure, updated it

2021-09-17 07:35 UTC, bb111189 approved these changes

2021-09-17 07:35 UTC, merged